### ISSUE TITLE
Kamerabild saknas

### ISSUE THREAD

**Issue by jonorland** [ricott/homey-se.trafikverket.vader#2]
Då man lägger till en ny Väderstation så kommer det inte alltid med möjlighet att se kamerabild. Ibland fungerar det och ibland inte.

**Comment by ricott** [comment]
Kör du nya Homey Pro 2023?

**Comment by jonorland** [comment]
Nej det är Homey Pro 2019. Fick en del timeout också, kanske relaterat?

**Comment by ricott** [comment]
Under settings på devicen finns det loggat last API error, kanske kan det ge något.
Du kan manuellt trigga en diagnostic report via appen, ibland kan den innehålla något.
Du kan också testa Homey web appen istället för mobilappen, bara för att se om det funkar där.
