### ISSUE TITLE
Och kort

### ISSUE THREAD

**Issue by Kingermann** [ricott/homey-se.trafikverket.vader#4]
Jag använder denna appen som en lokalväderstation istället för att ha en egen mätare på utsidan. Jag återkommer ganska ofta till att jag skulle vilja haft OCH kort. Typ "NÄR klockan är 8 => OCH regn < 0.1mm => SEDAN starta gräsklippare". Finns det nån tanke på att införa OCH kort här? 

Mvh

**Comment by ricott** [comment]
Regn som visas i appen idag är aggregat senaste 30 minuter.
Oklart om det är ett rullande fönster på 30 minuter, eller om detta värdet ex. aggregerats 09:00-09:30 för att då bli 0 kl 09:31 om det slutat regna under perioden. Finns inget i dokumentationen.

Kan absolut lägga till ett OCH kort för regn. Frågan är om det är användbart när det är för senaste 30 minuter? Eller vi måste hitta ett sätt att aggregerad det över dygnet?

**Comment by Kingermann** [comment]
Jag förstår. Jag tror att jag hade klarat mig ganska långt med 30 minuters intervall. I mitt specifika scenario så kan jag ju då använda regn kortet för att pausa min klippare i säg 4 timmar eller nåt. för att sen försöka starta den igen om parametrarna stämmer. Sen kan det ju absolut bli så att man ändå råkar starta den precis efter att regnet slutat ändå. Men önskvärt är ju också luftfuktighet. Då kan man kolla på dessa två tillsammans. 

Sen om detta är nånting som är värt för dig att lägga tid på vet jag inte. Det kanske är väldigt specifika scenarion för hur jag tänker och vill använda denna appen.

**Comment by ricott** [comment]
Regn finns som kort i [testversionen](https://homey.app/a/se.trafikverket.vader/test/) 👍

**Comment by Kingermann** [comment]
Jätte stort tack ! Jag tar ner den versionen och testar !
