### ISSUE TITLE
URL ändrad!

### ISSUE THREAD

**Issue by IcemanCharlie** [ricott/homey-se.trafikverket.vader#5]
Det fungerar inte med länken eftersom url:en är ändrad. Har inte hittat den nya än.

**Comment by ricott** [comment]
Behöver lite mer info, vilken länk talar vi om?

**Comment by IcemanCharlie** [comment]
Den du själv hänvisar till 😀

Find your weather station by visiting this url, https://www.trafikverket.se/trafikinformation/vag/?Layers=RoadWeather.


24 nov. 2023 kl. 15:48 skrev Richard Barkestam ***@***.***>:

﻿

Behöver lite mer info, vilken länk talar vi om?

**Comment by ricott** [comment]
ok, trodde det var den länken - men länken som sådan funkar. Sen är inte checkboxen för vägväder ifylld längre.
Länken verkar behöva lite fler parametrar för att visa hela vägen idag.

**Comment by IcemanCharlie** [comment]
Ja det fungerar ju redan med dom man har lagt till tidigare men om man skulle vilja lägga till en ny kommer det tydligen inte att fungera som det är nu. Har jag förstått det riktigt och är det något jag kan göra eller krävs det ”lite” arbete för dig 😜

Mv helg hälsning Michael

24 nov. 2023 kl. 16:39 skrev Richard Barkestam ***@***.***>:

﻿

ok, trodde det var den länken - men länken som sådan funkar. Sen är inte checkboxen för vägväder ifylld längre.
Länken verkar behöva lite fler parametrar för att visa hela vägen idag.

**Comment by ricott** [comment]
Tydligen får man inte ha en URL i readme längre, så plockar helt enkelt bort den.
https://apps.developer.homey.app/app-store/guidelines#1.3.-readme
Skapar en community sida istället som jag har för mina andra appar.

**Comment by ricott** [comment]
Version 0.9.9 är under granskning av Athom

**Comment by IcemanCharlie** [comment]
Toppen!
Detta ÄR en fantastisk app som jag använder dagligen så den bidrar till mycket! Hoppas att det går att lösa med Homey och trafikverket!!
Mycket snyggt jobbat 👍🏼

Med vänlig hälsning, Michael

28 nov. 2023 kl. 09:22 skrev Richard Barkestam ***@***.***>:

﻿

Closed #5<https://github.com/ricott/homey-se.trafikverket.vader/issues/5> as completed.
