### ISSUE TITLE
New forum page?

### ISSUE THREAD

**Issue by IcemanCharlie** [ricott/homey-se.trafikverket.vader#6]
I can see that you should have a new forum page for the Swedish Trafikverket Weather but I can’t find the www address ! /Michael

**Comment by ricott** [comment]
A bit hidden in the Homey App Store, but in the light grey box at the bottom of the page where you found the link to this GitHub repo. Label says Community, link says Visit forum...

https://community.homey.app/t/app-pro-swedish-trafikverket-weather/96077
